iPower PersonaCard 100/110
User Diagnostic Utilities
Version 1.1
Part Number 440010909-301
Revision B

Copyright (c) 1995
National Semiconductor Corporation
All Rights Reserved.

 Volume in drive A is HWDISK     
 Volume Serial Number is 1806-0A4E
 Directory of A:\

CAAPI    DLL     94572 04-12-95   5:18p
PCDIAG   EXE    113600 05-15-95   4:05p
PCDRIVER EXE     19119 01-23-95   9:51a
README   TXT     10720 05-23-95   5:13p
SETUP    EXE    283648 01-25-95  10:38a
SETUP    INS      5994 02-14-95  10:25a
SETUP    PKG        89 01-25-95   3:04p
909-301  B         686 06-09-95   6:22p
        8 file(s)     528428 bytes
                      927744 bytes free
